enyo.depends(
	"$lib/layout",
	"$lib/onyx",
	"$lib/layout/fittable/samples",
	"$lib/layout/panels/samples",
	"$lib/layout/list/samples",
	"$lib/layout/tree",
	"$lib/layout/tree/samples",
	"$lib/layout/imageview",
	"$lib/layout/imageview/samples",
	"$lib/onyx/samples",
	"$lib/canvas",
	"$lib/canvas/samples",
	"$enyo/samples",
	"App.css",
	"App.js"
);
